language: node_js
node_js:
  - "4"
dist: trusty
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - if [[ `npm -v` = 2* ]]; then npm i -g npm@3; fi
script:
  - grunt build
